### ISSUE TITLE
updating to 2.0 SDK

### ISSUE THREAD

**Issue by DidierA** [IEF/authenticator#18]
anybody working on porting this app to SDK 2.0 ? This way it could present a configuration pane on the phone to import tokens and configure timezone.

**Comment by calh** [comment]
I noticed on the live streaming presentation they said "GMT timezone functions to come soon" -- so I was just going to hang back until the SDK is a little more finalized.

A config screen would be very cool though.  It would be even cooler if there was the ability to dig into the private storage of Google Authenticator and automatically import secret keys!

**Comment by DidierA** [comment]
I have started working on it in my fork : https://github.com/DidierA/authenticator/tree/SDK-2.0
Currently the application works, but without the edit timezone screen.

**Comment by DidierA** [comment]
just submited a pull request : https://github.com/IEF/authenticator/pull/19
